# Generated by Django 3.1.3 on 2020-12-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=20, unique=True)),
                ('season', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='Olympic',
            fields=[
                ('olympic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('host_year', models.IntegerField()),
                ('season', models.CharField(max_length=4)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.city')),
            ],
            options={
                'db_table': 'Olympic',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.country'),
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.IntegerField(primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.country')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.sport')),
            ],
            options={
                'db_table': 'Athlete',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=40)),
                ('team', models.IntegerField()),
                ('medal_type', models.CharField(max_length=2)),
                ('olympic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.olympic')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.sport')),
            ],
            options={
                'db_table': 'Game',
                'unique_together': {('game_id', 'medal_type')},
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='olympicDB.game')),
                ('medal_type', models.CharField(max_length=2)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympicDB.athlete')),
            ],
            options={
                'db_table': 'Participate',
                'unique_together': {('athlete_id', 'medal_type', 'game_id')},
            },
        ),
    ]
