# Generated by Django 3.1.3 on 2020-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympicDB', '0002_auto_20201203_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
