# Generated by Django 3.1.3 on 2020-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympicDB', '0003_auto_20201203_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team',
        ),
    ]
