# Generated by Django 3.1.3 on 2020-12-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympicDB', '0004_remove_game_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gender',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
